- type: job
  id: AdministrativeAssistant
  name: job-name-admin-assistant
  description: job-description-admin-assistant
  playTimeTracker: JobAdminAssistant
  requirements:
  - !type:OverallPlaytimeRequirement # DeltaV - Playtime requirement
    time: 36000 # 10 hours - Omu start - around 5 full shifts, since they are mostly RP in addition to granting command hours.
  - !type:DepartmentTimeRequirement
    department: Engineering
    time: 18000 #5 hours - Omu edit
  - !type:DepartmentTimeRequirement
    department: Security
    time: 18000 #5 hours - Omu edit
  - !type:DepartmentTimeRequirement
    department: Science
    time: 18000 #5 hours - Omu edit
  - !type:DepartmentTimeRequirement
    department: Medical
    time: 18000 #5 hours - Omu edit end
  goobcoins: 20 # Goob Content
  startingGear: AdminAssistantGear
  icon: "JobIconAdminAssitant"
  supervisors: job-supervisors-command
  canBeAntag: true # Goob - Changed to true for Corpo Agents
  access:
  - Command
  - Maintenance
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
    - type: CommandStaff # Goob - Left this here so they won't be other antags; BSO should just not implant them.

- type: startingGear
  id: AdminAssistantGear
  equipment:
    eyes: ClothingEyesHudCommand
    belt: BoxFolderClipboard
    id: AdminAssistantPDA
    pocket1: RubberStampAdminAssistant
  storage:
    back:
    - Flash

# Omu Station Reqs
- type: chameleonOutfit
  id: AdminAssistantChameleonOutfit
  job: AdministrativeAssistant
  hasMindShield: true
  equipment:
    eyes: ClothingEyesGlasses
    mask: ClothingMaskGas
    neck: ClothingNeckScarfStripedGreen
    outerClothing: ClothingOuterWinterColorGreen
    gloves: ClothingHandsGlovesColorBlack
